"""
IMplement different cost dunctions for the 
optimization of the MR Fingerprinting sequence.

@author: Jannik Stebani 2025
"""
import jax
from jax.typing import Array, Scalar

from mrfoptools.epg.signal import PreparationType

from mrfoptools.epg.signal import compute_signal_optimized

# @jax.jit(static_argnames=('preparation', 'inversion_efficiency', 'delta_B1'))
def orthogonality_criterion(
        T1: Array,
        T2: Array,
        fa: Array,
        TR: Array,
        phases: Array,
        preparation: PreparationType,
        TI: Array,
        TE: float,
        inversion_efficiency: float,
        delta_B1: float
) -> Scalar:
    """
    Compute the orthogonality criterion for all (T1, T2)-wise signals
    generated by the specified MR Fingerprinting sequence.

    Parameters
    ----------

    T1 : Array
        T1 relaxation time in seconds.

    T2 : Array
        T2 relaxation time in seconds.

    fa : Array
        Flip angles in degrees.

    TR : Array
        Repetition time in seconds.

    phases : Array
        Phase offsets in degrees.

    preparation : PreparationType
        Preparation type.

    TI : Array
        Inversion time in seconds.

    TE : float
        Echo time in seconds.

    inversion_efficiency : float
        Inversion efficiency.

    delta_B1 : float
        B1 inhomogeneity in percent.

    Returns
    -------

    orthogonality_criterion : float
        Orthogonality criterion.
    """
    
    # Parallelize computation of different sigals.
    for 
    

    # Compute the orthogonality criterion.
    return jnp.linalg.norm(jnp.dot(S.T, S) - jnp.eye(S.shape[1]))