"""
IMplement different cost dunctions for the 
optimization of the MR Fingerprinting sequence.

@author: Jannik Stebani 2025
"""
import jax.numpy as jnp
from jax import Array

import mrfoptools.epg.core as epg
import mrfoptools.epg.signal.signal as epgsig



def orthogonality_criterion(signals: Array) -> Array:
    """
    Cost function for the total pairwise orthogonality of the signals.
    Note: Signals are assumed to be normalized.

    Parameters
    ----------

    signals : Array
        Signals array of the shape (n_species, n_shots).

    Returns
    -------

    cost : Array
        Orthogonality criterion.
    """
    n_species, _ = signals.shape
    return jnp.linalg.norm(jnp.eye(n_species) - signals @ jnp.conjugate(signals.T))


# @jax.jit(static_argnames=('preparation', 'inversion_efficiency', 'delta_B1'))
def legacy_orthogonality_criterion(
        T1: Array,
        T2: Array,
        M0: float,
        fa: Array,
        TR: Array,
        phases: Array,
        preparation: epgsig.PreparationType,
        TI: Array,
        TE: float,
        inversion_efficiency: float = 1.0,
        delta_B1: float = 1.0
) -> Array:
    """
    Compute the orthogonality criterion for all (T1, T2)-wise signals
    generated by the specified MR Fingerprinting sequence.

    Parameters
    ----------

    T1 : Array
        T1 relaxation time in seconds.

    T2 : Array
        T2 relaxation time in seconds.

    fa : Array
        Flip angles in radians.

    TR : Array
        Repetition time in seconds.

    phases : Array
        Phase offsets in radians.

    preparation : PreparationType
        Preparation type.

    TI : Array
        Inversion time in seconds.

    TE : float
        Echo time in seconds.

    inversion_efficiency : float
        Inversion efficiency.

    delta_B1 : float
        B1 inhomogeneity in percent.

    Returns
    -------

    orthogonality_criterion : float
        Orthogonality criterion.
    """
    MAX_STATES: int = 1000

    '''
    if preparation is epgsig.PreparationType.NONE:
        omega = epgsig.prepare_equilibrium_omega(M0, max_states=MAX_STATES)
    elif preparation is epgsig.PreparationType.INVERSION:
        omega = epgsig.prepare_inversion_omega(
            M0, inversion_efficiency, max_states=MAX_STATES
        )

    # Partial application of arguments: expected remaining args
    # are the species-specific relaxometric parameters (T1, T2)
    # and the individual starting state omega
    # TODO: this was a safety measure against state mutation: is this fear real?
    # Intention: Clearer vmap vectorization across (T1, T2) pairs
    compute_signal = functools.partial(
        epgsig.compute_signal,
        fa=fa,
        phases=phases,
        M0=M0,
        TR=TR,
        TE=TE,
        b_TE=b_TE,
        r_TE=r_TE
    )
    '''
    n_shots: int = len(fa)
    n_species: int = len(T1)
    assert n_shots == len(TR) == len(phases), 'time dimension length mismatch'
    assert n_species == len(T2), 'species dimension length mismatch'

    # conversion
    fa = fa *  delta_B1
    phases = phases

    # precompute echo time operators

    signals = jnp.zeros((n_species, n_shots), dtype=jnp.complex64)

    for idx in range(n_species):

        b_TE = epg.b_epg(T1=T1[idx], dt=TE)
        r_TE = epg.r_epg(T1=T1[idx], T2=T2[idx], dt=TE)
        inv_op = epg.inversion(inversion_efficiency)

        omega = epgsig.prepare_inversion_omega(T1=T1[idx], T2=T2[idx],
                                               M0=M0,
                                               TI=TI,
                                               inversion_operator=inv_op,
                                               max_states=MAX_STATES)
        
        # Compute the signal for the current (T1, T2) pair
        s = epgsig.compute_signal_optimized(
            omega=omega,
            T1=T1[idx],
            T2=T2[idx],
            M0=M0,
            fa=fa,
            phases=phases,
            TR=TR,
            TE=TE,
            b_TE=b_TE,
            r_TE=r_TE
        )
        signals = signals.at[idx].set(s)

    signals = signals / jnp.linalg.norm(signals, ord=2, axis=1, keepdims=True)

    cost = jnp.linalg.norm(jnp.eye(n_species) - signals @ jnp.conjugate(signals.T))

    # cost2 = jnp.linalg.norm(fa[:-1] - fa[1:], ord=2) / fa.size

    return cost #+ cost2