# build and installation instructions for woodnet
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mrfoptools"
version = "0.0.1"
authors = [
  { name="Jannik Stebani", email="jannik.stebani@uni-wuerzburg.de" },
]
description = "Programmatic optimization of flip angle trains for MRF-like sequences."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta"
]
license = {file = "LICENSE.txt"}
keywords = [
    "magnetic resonance imaging", "machine learning", "automatic differentiation",
    "image processing", "machine learning", "signal processing"]

dependencies = [
  "jax",
  "numpy",
  "torch",
  "torchvision",
  "torchaudio",
  "matplotlib",
  "tqdm",
  "tensorboard",
  "rich",
  "scikit-learn",
  "scikit-image",
  "pytest",
  "optax",
  "zarr >= 3.0",
  "numba",
  "attrs",
  "qpsolvers"
]

[project.urls]
Homepage = "https://github.com/stebix/mrfoptools"
Issues = "https://github.com/stebix/mrfoptools/issues"

[tool.ruff]
exclude = ["legacy"]
line-length = 99
indent-width = 4

[tool.pytest.ini_options]
markers = [
    "slow: mark a test that takes a long time to run.",
    "benchmark: mark test that are benchmarks with CLI output intended for human inspection"
]