"""
Tooling for gradient and cost diagnostics: Logging and visualization to tensorboard.

@Author: Jannik Stebani 2025
"""
import enum
from collections.abc import Mapping, Callable
import numpy as np
import jax
import matplotlib.pyplot as plt
from torch.utils.tensorboard import SummaryWriter

from mrfoptools.optimization.costgrad import NumpyCostGradTuple


class CostValueRange(enum.Enum):
    POSITIVE = 'positive'
    NEGATIVE = 'negative'


def log_costs(
    cost_grad_mapping: Mapping[str, NumpyCostGradTuple],
    writer: SummaryWriter,
    iteration: int
) -> None:
    """
    Log scalar cost values for arbitrary (sub-) objectives to a summary writer.
    """
    prefix: str = 'costs'
    for name, cg_tuple in cost_grad_mapping.items():
        tag = '/'.join((prefix, name))
        writer.add_scalar(tag=tag, scalar_value=cg_tuple.cost, global_step=iteration)


def log_gradient_histograms(
    cost_grad_mapping: Mapping[str, NumpyCostGradTuple],
    writer: SummaryWriter,
    iteration: int
) -> None:
    """
    Log gradient as histograms.
    """
    prefix: str = 'gradhists'
    for name, cg_tuple in cost_grad_mapping.items():
        tag = '/'.join((prefix, name))
        writer.add_histogram(tag=tag, values=cg_tuple.grad.ravel(), global_step=iteration)


def log_cosine_similarities(
    cosine_similarities: Mapping[str, float],
    writer: SummaryWriter,
    iteration: int
) -> None:
    """
    Log precomputed cosine similarites to a summary writer instance.
    """
    prefix: str = 'grad_cos_sim'
    for name, value in cosine_similarities.items():
        tag = '/'.join((prefix, name))
        writer.add_scalar(tag=tag, scalar_value=value, global_step=iteration)
    
    
def log_gradient_magnitude_similarities(
    magnitude_similarities: Mapping[str, float],
    writer: SummaryWriter,
    iteration: int
) -> None:
    """
    Log precomputed gradient magnitude similarities to a summary writer instance.
    """
    prefix: str = 'grad_mag_sim'
    for name, value in magnitude_similarities.items():
        tag = '/'.join((prefix, name))
        writer.add_scalar(tag=tag, scalar_value=value, global_step=iteration)


def build_relative_gain_logfunction(
    forward: Callable[[jax.Array, jax.Array, jax.Array], jax.Array],
    initial_parameters: tuple[jax.Array, jax.Array],
    criterion: Callable[[jax.Array], jax.Array],
    writer: SummaryWriter,
    name: str,
    prefix: str = 'relative_gain',
    cost_value_range: CostValueRange | str = CostValueRange.POSITIVE
) -> Callable:
    """
    Programmatically log improvements of a scalar cost value
    relative to a predefined initial value.
    """
    out = forward(*initial_parameters)
    init_cost = np.asarray(criterion(out))
    tag = '/'.join((prefix, name))

    # For relative gain, we have to make a case distinction for 
    # cost functions that generate strictly positive or negative values.
    cost_value_range = CostValueRange(cost_value_range) if not isinstance(cost_value_range, CostValueRange) else cost_value_range
    if cost_value_range == CostValueRange.POSITIVE:
        def _log(cg_tuple: NumpyCostGradTuple, iteration: int):
            """Log relative gain over initial baseline cost value."""
            relative_improvement = init_cost / cg_tuple.cost
            writer.add_scalar(tag=tag, scalar_value=relative_improvement, global_step=iteration)
    
    elif cost_value_range == CostValueRange.NEGATIVE:
        # Due to cancelling of the negative sign, we have to invert the fraction.
        # A 'larger' cost value (absolute value wise) is actually a 'better' solution.
        def _log(cg_tuple: NumpyCostGradTuple, iteration: int):
            """Log relative gain over initial baseline cost value."""
            relative_improvement = cg_tuple.cost / init_cost
            writer.add_scalar(tag=tag, scalar_value=relative_improvement, global_step=iteration)
            
    return _log


def signal_log_builder(
    forward: Callable[[jax.Array, jax.Array, jax.Array], jax.Array],
    T1: jax.Array,
    T2: jax.Array,
    writer: SummaryWriter,
    initial_signals: np.ndarray | None = None
) -> Callable[[jax.Array, int], None]:
    """
    Build a function to log the signals generated by the sequence in the current
    iteration.
    """
    prefix: str = 'plots'
    tag: str = '/'.join((prefix, 'signals'))
    initial_signals_plot_settings = {'linestyle' : 'dotted', 'alpha' : 0.7}
    
    def _log_signals(fa: jax.Array, iteration: int):
        """Compute signals, create figure and write to summary.
        
        Parameters
        ----------
        fa: jax.Array
            Flip angles in radians.
        """
        signals = forward(T1, T2, fa)
        n_species, _ = signals.shape
        fig, ax = plt.subplots()
        for i in range(n_species):
            ax.plot(signals[i, :].imag)
            if initial_signals is not None:
                ax.plot(
                    initial_signals[i, :].imag,
                    **initial_signals_plot_settings
                )
        writer.add_figure(tag=tag, figure=fig, global_step=iteration, close=True)
        
    return _log_signals
        
    