"""
Tooling for gradient and cost diagnostics: Logging and visualization to tensorboard.

@Author: Jannik Stebani 2025
"""
from collections.abc import Mapping, Callable
import numpy as np
import jax
import matplotlib.pyplot as plt
from torch.utils.tensorboard import SummaryWriter

from mrfoptools.optimization.costgrad import CostContainer, GradientContainer


def log_costs(
    cost_mapping: Mapping[str, CostContainer],
    writer: SummaryWriter,
    iteration: int
) -> None:
    """
    Log scalar cost values for arbitrary (sub-) objectives to a summary writer.
    """
    prefix: str = 'costs'
    for name, cost_container in cost_mapping.items():
        tag = '/'.join((prefix, name))
        writer.add_scalar(tag=tag, scalar_value=cost_container.cost, global_step=iteration)


def log_gradient_histograms(
    grad_mapping: Mapping[str, GradientContainer],
    writer: SummaryWriter,
    iteration: int
) -> None:
    """
    Log gradient as histograms.
    """
    prefix: str = 'gradhists'
    for name, grad_container in grad_mapping.items():
        tag = '/'.join((prefix, name))
        writer.add_histogram(tag=tag, values=grad_container.grad.ravel(), global_step=iteration)


def log_cosine_similarities(
    cosine_similarities: Mapping[str, float],
    writer: SummaryWriter,
    iteration: int
) -> None:
    """
    Log precomputed cosine similarites to a summary writer instance.
    """
    prefix: str = 'grad_cos_sim'
    for name, value in cosine_similarities.items():
        tag = '/'.join((prefix, name))
        writer.add_scalar(tag=tag, scalar_value=value, global_step=iteration)
    
    
def log_gradient_magnitude_similarities(
    magnitude_similarities: Mapping[str, float],
    writer: SummaryWriter,
    iteration: int
) -> None:
    """
    Log precomputed gradient magnitude similarities to a summary writer instance.
    """
    prefix: str = 'grad_mag_sim'
    for name, value in magnitude_similarities.items():
        tag = '/'.join((prefix, name))
        writer.add_scalar(tag=tag, scalar_value=value, global_step=iteration)


def signal_log_builder(
    forward: Callable[[jax.Array, jax.Array, jax.Array], jax.Array],
    T1: jax.Array,
    T2: jax.Array,
    writer: SummaryWriter,
    initial_signals: np.ndarray | None = None
) -> Callable[[jax.Array, int], None]:
    """
    Build a function to log the signals generated by the sequence in the current
    iteration.
    """
    prefix: str = 'plots'
    tag: str = '/'.join((prefix, 'signals'))
    initial_signals_plot_settings = {'linestyle' : 'dotted', 'alpha' : 0.7}
    
    def _log_signals(fa: jax.Array, iteration: int):
        """Compute signals, create figure and write to summary.
        
        Parameters
        ----------
        fa: jax.Array
            Flip angles in radians.
        """
        signals = forward(T1, T2, fa)
        n_species, _ = signals.shape
        fig, ax = plt.subplots()
        for i in range(n_species):
            ax.plot(signals[i, :].imag)
            if initial_signals is not None:
                ax.plot(
                    initial_signals[i, :].imag,
                    **initial_signals_plot_settings
                )
        writer.add_figure(tag=tag, figure=fig, global_step=iteration, close=True)
        
    return _log_signals
        
    